export const infoTabs = document.querySelectorAll('.app__weather-top');
export const tabsSection = document.querySelector('.app__weather-tabs');
export const allTabs = document.querySelectorAll('.app__weather-tab');
export const weatherInformation = document.querySelector('.weather-information__temperature');
export const weatherFeelsLike = document.querySelector('.weather-information__feelsLike');
export const weather = document.querySelector('.weather-information__weather');
export const weatherSunrise = document.querySelector('.weather-information__sunrise')
export const weatherSunset = document.querySelector('.weather-information__sunset')
export const weatherCity = document.querySelector('.app__weather-city');
export const weatherCityDetails = document.querySelector('.app__weather-city--details');
export const weatherCityFavourite = document.querySelector('.app__weather-city--favourite');
export const weatherCityForecast = document.querySelector('.app__weather-city--forecast');
export const inputValue = document.querySelector('.app__search-input')
export const btn = document.querySelector('.app__search-button');
// export const favouriteCity = document.querySelector('.weather__favourite');
export const addedLocations = document.querySelector('.app__locations-list');
export const weatherDigitsValue = document.querySelector('.weather__value');
export const weatherIcon = document.querySelector('.weather__icon');
export const dailyForecast = document.querySelector('.app__weather-daily')
export const hourlyForecast = document.querySelector('.app__weather-hourly');
export const weatherSwitcher = document.querySelector('.weather-checkbox__more')
export let set = new Set();